name: lint

on: [pull_request]

jobs:
  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-latest
    steps:
      - name: clang-tidy check
        uses: Tlazypanda/cpp-clang-check@master
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
